# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.1.1
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.4.0
    hooks:
    -   id: pyupgrade
        args: ['--py3-plus','--py36-plus']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace  # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
    -   id: no-commit-to-branch  # 禁止直接向master分支commit
        args: ['--branch', 'master']
    -   id: end-of-file-fixer  # Makes sure files end in a newline and only a newline.
    -   id: check-yaml  # Attempts to load all yaml files to verify syntax.
#    -   id: check-added-large-files  # Prevent giant files from being committed.
#   由于python3默认编码即为utf-8,所有这里不再添加编码声明，而且该声明与pyupgrade的参数冲突
#    -   id: fix-encoding-pragma  # Add # -*- coding: utf-8 -*- to the top of python files.
    -   id: requirements-txt-fixer  # Sorts entries in requirements.txt and removes incorrect entry
#-   repo: https://github.com/Trim21/mirrors-autoflake
#    rev: v1.3.1
#    hooks:
#    -   id: autoflake
#        args: ['--in-place']
#   isort与black冲突，使用reorder_python_imports代替
#-   repo: https://github.com/timothycrosley/isort
#    rev: 4.3.21  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
#    hooks:
#    -   id: isort
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5
    hooks:
    -   id: autopep8
        args: ['-i','--list-fixes']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: docs/
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        language_version: python3
        exclude: ^tests/
#-   repo: local
#    hooks:
#    -   id: system
#        name: PyLint
#        entry: python -m pylint.__main__
#        language: system
#        files: \.py$
#-   repo: local
#    hooks:
#    -   id: tests
#        name: run tests
#        entry: pytest -v
#        language: system
#        types: [python]
#        stages: [push]
